### PR TITLE
Date range picker feature.

### PR DESCRIPTION
**Pull request by commandiron**
This pr fix [this](https://github.com/hi-manshu/Kalendar/issues/26#issue-1119866205) issue.

Include;
kalendar-endloss package -> Kalendar
kalendar package -> Kalendar (Firey), I thought Oceanic was not needed but it can be added later.

### CODE REVIEW

**Comment by hi-manshu** [comment]
@commandiron thank you for doing this. Have few Nits
1. Chekc the Code Style
2. Upon Selection there is a few change needed for condition check

**Comment by commandiron** [comment]
hi, i don't know how to do ktlint check, but i will find out and review my code again. Thank you.

**Comment by hi-manshu** [comment]
> hi, i don't know how to do ktlint check, but i will find out and review my code again. Thank you.

Yes please do, and thank you for the effort.

**Comment by gsrathoreniks** [comment]
@commandiron
1. When selected the range it should return the selected range else it'll be of no use.

**Comment by commandiron** [comment]
@gsrathoreniks 

You're right, I'll add this.

**Comment by gsrathoreniks** [comment]
@commandiron 
I think returning pair of dates is better option. I think LocalDate is fine.


If we use **onCurrentDayClick** then the user will have to keep record of the first date selected, because when second date will be clicked it will replace the data. So it's better to pair of date with a new function.

Thought: if we make the `onDateRangeSelected` parameter optional then it'll be better because we won't have to add it in case we don't want to use the Range.

**Comment by commandiron** [comment]
I cant solve this conflict, don't know why, any help?

**Pull request closed without merging**
