### PR TITLE
Added multi lingual support for Oceanic calendar's weeknames

### LINKED ISSUE #160: Showing the week value(mon~sun) is different of two view
Two month-week calendars are implemented using the type KalendarType.Oceanic and KalendarType.Firey. Oceanic type shows the value of week in English, while Firey type shows the value of week in Korean.
Is there a method or property that integrates these two environments into one language?

i1
i2

### PR DESCRIPTION
**Pull request by gsrathoreniks**
Closes #160

### CODE REVIEW

**Review by Afolayan — COMMENTED** [review]
Your branch name reads fix/Oceanic_language, but the changes are in KalendarFirey.kt. This is a bit confusing.
According to the linked issue, Firey is already localised but Oceanic is not. Can you clarify this?

**Comment by gsrathoreniks** [comment]
@Afolayan I created the branch based on #160  where it was wrongly mentioned between the two. I guess I forgot to rename the branch before pushing.

**Comment by Afolayan** [comment]
Would you be able to rename the branch for clarity, so we can merge this PR?

**Comment by gsrathoreniks** [comment]
@Afolayan 
Changed name and created new PR #165 
we can close this one.

**Pull request closed without merging**
