### PR TITLE
Customization of the initial day of the week in KalendarKonfig

### PR DESCRIPTION
**Pull request by jeluchu**
A new parameter called `isMondayInitialDay` of type Boolean is included in **KalendarKonfig**, in which we can indicate if the first day of the week is Monday (if true) and if not, the initial day would be Sunday

### CODE REVIEW

**Comment by carstenhag** [comment]
Thanks for making it work for other parts of the world ;) It must be something else than a boolean though, because it's not saturday or monday, it's rather more colorful:

CLDR 40 has territories starting the week with friday, saturday, sunday, monday: https://unicode-org.github.io/cldr-staging/charts/40/supplemental/territory_information.html

**Comment by hi-manshu** [comment]
@jeluchu please check the code?

**Comment by jeluchu** [comment]
@hi-manshu I am reviewing another way of doing it so that it can be applied with the different countries as you have indicated within the issue

**Comment by hi-manshu** [comment]
Its fixed, Thanks for doing it

**Pull request closed without merging**
